In [278]:
import pandas as pd
import numpy as np

In [279]:
df=pd.read_csv('df_arabica_clean.csv')
df.head(3)

,Unnamed: 0,ID,Country of Origin,Farm Name,Lot Number,Mill,ICO Number,Company,Altitude,Region,...,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Expiration,Certification Body,Certification Address,Certification Contact
0,0,0,Colombia,Finca El Paraiso,CQU2022015,Finca El Paraiso,NaN,Coffee Quality Union,1700-1930,"Piendamo,Cauca",...,89.33,11.8,0,0,green,3,"September 21st, 2023",Japan Coffee Exchange,"〒413-0002 静岡県熱海市伊豆山１１７３−５８ 1173-58 Izusan, Ata...",松澤 宏樹 Koju Matsuzawa - +81(0)9085642901
1,1,1,Taiwan,Royal Bean Geisha Estate,"The 2022 Pacific Rim Coffee Summit,T037",Royal Bean Geisha Estate,NaN,Taiwan Coffee Laboratory,1200,Chiayi,...,87.58,10.5,0,0,blue-green,0,"November 15th, 2023",Taiwan Coffee Laboratory 台灣咖啡研究室,"QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd...","Lin, Jen-An Neil 林仁安 - 886-289116612"
2,2,2,Laos,OKLAO coffee farms,"The 2022 Pacific Rim Coffee Summit,LA01",oklao coffee processing plant,NaN,Taiwan Coffee Laboratory,1300,Laos Borofen Plateau,...,87.42,10.4,0,0,yellowish,2,"November 15th, 2023",Taiwan Coffee Laboratory 台灣咖啡研究室,"QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd...","Lin, Jen-An Neil 林仁安 - 886-289116612"

In [280]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             207 non-null    int64
 1   ID                     207 non-null    int64
 2   Country of Origin      207 non-null    object
 3   Farm Name              205 non-null    object
 4   Lot Number             206 non-null    object
 5   Mill                   204 non-null    object
 6   ICO Number             75 non-null     object
 7   Company                207 non-null    object
 8   Altitude               206 non-null    object
 9   Region                 205 non-null    object
 10  Producer               206 non-null    object
 11  Number of Bags         207 non-null    int64
 12  Bag Weight             207 non-null    object
 13  In-Country Partner     207 non-null    object
 14  Harvest Year           207 non-null    object
 15  Grading Date           207 non-null    object
 16  Owner                  207 non-null    object
 17  Variety                201 non-null    object
 18  Status                 207 non-null    object
 19  Processing Method      202 non-null    object
 20  Aroma                  207 non-null    float64
 21  Flavor                 207 non-null    float64
 22  Aftertaste             207 non-null    float64
 23  Acidity                207 non-null    float64
 24  Body                   207 non-null    float64
 25  Balance                207 non-null    float64
 26  Uniformity             207 non-null    float64
 27  Clean Cup              207 non-null    float64
 28  Sweetness              207 non-null    float64
 29  Overall                207 non-null    float64
 30  Defects                207 non-null    float64
 31  Total Cup Points       207 non-null    float64
 32  Moisture Percentage    207 non-null    float64
 33  Category One Defects   207 non-null    int64
 34  Quakers                207 non-null    int64
 35  Color                  207 non-null    object
 36  Category Two Defects   207 non-null    int64
 37  Expiration             207 non-null    object
 38  Certification Body     207 non-null    object
 39  Certification Address  207 non-null    object
 40  Certification Contact  207 non-null    object
dtypes: float64(13), int64(6), object(22)
memory usage: 66.4+ KB

In [281]:
df.isna().sum()

Unnamed: 0                 0
ID                         0
Country of Origin          0
Farm Name                  2
Lot Number                 1
Mill                       3
ICO Number               132
Company                    0
Altitude                   1
Region                     2
Producer                   1
Number of Bags             0
Bag Weight                 0
In-Country Partner         0
Harvest Year               0
Grading Date               0
Owner                      0
Variety                    6
Status                     0
Processing Method          5
Aroma                      0
Flavor                     0
Aftertaste                 0
Acidity                    0
Body                       0
Balance                    0
Uniformity                 0
Clean Cup                  0
Sweetness                  0
Overall                    0
Defects                    0
Total Cup Points           0
Moisture Percentage        0
Category One Defects       0
Quakers                    0
Color                      0
Category Two Defects       0
Expiration                 0
Certification Body         0
Certification Address      0
Certification Contact      0
dtype: int64

In [282]:
df.columns

Index(['Unnamed: 0', 'ID', 'Country of Origin', 'Farm Name', 'Lot Number',
       'Mill', 'ICO Number', 'Company', 'Altitude', 'Region', 'Producer',
       'Number of Bags', 'Bag Weight', 'In-Country Partner', 'Harvest Year',
       'Grading Date', 'Owner', 'Variety', 'Status', 'Processing Method',
       'Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance',
       'Uniformity', 'Clean Cup', 'Sweetness', 'Overall', 'Defects',
       'Total Cup Points', 'Moisture Percentage', 'Category One Defects',
       'Quakers', 'Color', 'Category Two Defects', 'Expiration',
       'Certification Body', 'Certification Address', 'Certification Contact'],
      dtype='object')

In [283]:
#dropping 'Unnamed: 0', 'ID'
df.drop(['Unnamed: 0', 'ID','ICO Number'],axis=1,inplace=True)

In [284]:
df.head(2)

,Country of Origin,Farm Name,Lot Number,Mill,Company,Altitude,Region,Producer,Number of Bags,Bag Weight,...,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Expiration,Certification Body,Certification Address,Certification Contact
0,Colombia,Finca El Paraiso,CQU2022015,Finca El Paraiso,Coffee Quality Union,1700-1930,"Piendamo,Cauca",Diego Samuel Bermudez,1,35 kg,...,89.33,11.8,0,0,green,3,"September 21st, 2023",Japan Coffee Exchange,"〒413-0002 静岡県熱海市伊豆山１１７３−５８ 1173-58 Izusan, Ata...",松澤 宏樹 Koju Matsuzawa - +81(0)9085642901
1,Taiwan,Royal Bean Geisha Estate,"The 2022 Pacific Rim Coffee Summit,T037",Royal Bean Geisha Estate,Taiwan Coffee Laboratory,1200,Chiayi,曾福森,1,80 kg,...,87.58,10.5,0,0,blue-green,0,"November 15th, 2023",Taiwan Coffee Laboratory 台灣咖啡研究室,"QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd...","Lin, Jen-An Neil 林仁安 - 886-289116612"

In [285]:
df.dropna(inplace=True,axis=1)

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country of Origin      207 non-null    object
 1   Company                207 non-null    object
 2   Number of Bags         207 non-null    int64
 3   Bag Weight             207 non-null    object
 4   In-Country Partner     207 non-null    object
 5   Harvest Year           207 non-null    object
 6   Grading Date           207 non-null    object
 7   Owner                  207 non-null    object
 8   Status                 207 non-null    object
 9   Aroma                  207 non-null    float64
 10  Flavor                 207 non-null    float64
 11  Aftertaste             207 non-null    float64
 12  Acidity                207 non-null    float64
 13  Body                   207 non-null    float64
 14  Balance                207 non-null    float64
 15  Uniformity             207 non-null    float64
 16  Clean Cup              207 non-null    float64
 17  Sweetness              207 non-null    float64
 18  Overall                207 non-null    float64
 19  Defects                207 non-null    float64
 20  Total Cup Points       207 non-null    float64
 21  Moisture Percentage    207 non-null    float64
 22  Category One Defects   207 non-null    int64
 23  Quakers                207 non-null    int64
 24  Color                  207 non-null    object
 25  Category Two Defects   207 non-null    int64
 26  Expiration             207 non-null    object
 27  Certification Body     207 non-null    object
 28  Certification Address  207 non-null    object
 29  Certification Contact  207 non-null    object
dtypes: float64(13), int64(4), object(13)
memory usage: 48.6+ KB

In [287]:

df.drop(['Certification Address', 'Certification Contact','Expiration','In-Country Partner','Status','Grading Date','Owner'],axis=1,inplace=True)

In [288]:
df.head(2)

,Country of Origin,Company,Number of Bags,Bag Weight,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,...,Sweetness,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Certification Body
0,Colombia,Coffee Quality Union,1,35 kg,2021 / 2022,8.58,8.5,8.42,8.58,8.25,...,10.0,8.58,0.0,89.33,11.8,0,0,green,3,Japan Coffee Exchange
1,Taiwan,Taiwan Coffee Laboratory,1,80 kg,2021 / 2022,8.50,8.5,7.92,8.00,7.92,...,10.0,8.50,0.0,87.58,10.5,0,0,blue-green,0,Taiwan Coffee Laboratory 台灣咖啡研究室

In [289]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country of Origin     207 non-null    object
 1   Company               207 non-null    object
 2   Number of Bags        207 non-null    int64
 3   Bag Weight            207 non-null    object
 4   Harvest Year          207 non-null    object
 5   Aroma                 207 non-null    float64
 6   Flavor                207 non-null    float64
 7   Aftertaste            207 non-null    float64
 8   Acidity               207 non-null    float64
 9   Body                  207 non-null    float64
 10  Balance               207 non-null    float64
 11  Uniformity            207 non-null    float64
 12  Clean Cup             207 non-null    float64
 13  Sweetness             207 non-null    float64
 14  Overall               207 non-null    float64
 15  Defects               207 non-null    float64
 16  Total Cup Points      207 non-null    float64
 17  Moisture Percentage   207 non-null    float64
 18  Category One Defects  207 non-null    int64
 19  Quakers               207 non-null    int64
 20  Color                 207 non-null    object
 21  Category Two Defects  207 non-null    int64
 22  Certification Body    207 non-null    object
dtypes: float64(13), int64(4), object(6)
memory usage: 37.3+ KB

In [290]:
df['Country of Origin'].value_counts()

Country of Origin
Taiwan                          61
Guatemala                       21
Colombia                        19
Honduras                        13
Thailand                        12
Ethiopia                        11
Brazil                          10
Costa Rica                       8
Nicaragua                        7
El Salvador                      7
Tanzania, United Republic Of     6
United States (Hawaii)           5
Mexico                           4
Peru                             4
Vietnam                          4
Uganda                           3
Indonesia                        3
Laos                             3
Panama                           2
Kenya                            2
Madagascar                       1
Myanmar                          1
Name: count, dtype: int64

In [291]:
df['Company'].value_counts()

Company
Taiwan Coffee Laboratory        51
Taiwu Coffee Cooperative        25
Coffee Quality Union            15
Doi Tung Development Project     7
Peter Schoenfeld, S.A.           6
                                ..
Taylor Winch Coffee Ltd          1
ECOM COLOMBIA                    1
Exportadora Café California      1
Coffee Quality Institute         1
marubeni                         1
Name: count, Length: 72, dtype: int64

In [292]:
df['Harvest Year'].value_counts()

Harvest Year
2021 / 2022    99
2022           48
2022 / 2023    42
2021           13
2023            3
2017 / 2018     1
2018 / 2019     1
Name: count, dtype: int64

In [293]:
df['Harvest Year']=df['Harvest Year'].map({'2021 / 2022':'2021','2022 / 2023':'2022','2017 / 2018':'2017','2018 / 2019':'2018','2022':'2022','2021':'2021','2023':'2023'})

In [294]:
df['Harvest Year'].value_counts()

Harvest Year
2021    112
2022     90
2023      3
2017      1
2018      1
Name: count, dtype: int64

In [295]:
df['Number of Bags'].value_counts()

Number of Bags
1       62
275     16
320     14
2       11
600     10
5        7
3        6
200      5
300      4
4        4
10       4
6        3
8        3
250      3
325      3
20       3
100      3
260      3
345      2
16       2
620      2
9        2
440      2
40       2
960      1
26       1
2240     1
141      1
22       1
540      1
150      1
32       1
77       1
13       1
125      1
500      1
14       1
120      1
55       1
50       1
285      1
635      1
375      1
35       1
430      1
19       1
584      1
340      1
74       1
66       1
632      1
80       1
25       1
70       1
343      1
Name: count, dtype: int64

In [296]:
df['Bag Weight'].value_counts()

Bag Weight
30 kg       39
60 kg       31
69 kg       25
1 kg        14
15 kg       10
5 kg        10
2 kg         8
70 kg        6
100 kg       6
50 kg        6
10 kg        5
80 kg        4
35 kg        4
20 kg        3
12 kg        3
4 kg         2
25 kg        2
90 kg        2
45 kg        2
16 kg        2
13 kg        2
22 kg        2
19200 kg     2
8 kg         2
40 kg        1
32 kg        1
200 kg       1
3 kg         1
320 kg       1
6 kg         1
104 kg       1
110 kg       1
300 kg       1
36 kg        1
24 kg        1
48 kg        1
85 kg        1
27 kg        1
59 kg        1
Name: count, dtype: int64

In [297]:
#dropping Bag Weight,Number of Bags as they dont indicate quality

In [298]:
df['Certification Body'].value_counts()

Certification Body
Taiwan Coffee Laboratory 台灣咖啡研究室                                     83
Japan Coffee Exchange                                                27
Asociacion Nacional Del Café                                         14
Instituto Hondureño del Café                                         10
FABB Academy of Coffee                                                9
Kenya Coffee Traders Association                                      8
Specialty Coffee Association of Costa Rica                            7
Blossom Valley International宸嶧國際                                      6
METAD Agricultural Development plc                                    6
Salvadoran Coffee Council                                             6
Centro Agroecológico del Café A.C.                                    5
Brazil Specialty Coffee Association                                   4
NKG Quality Service (a division of Bernhard Rothfos Intercafé AG)     4
Specialty Coffee Association                                          4
ASOCIACIÓN COLOMBIANA PARA LA EXCELENCIA DEL CAFE                     4
Uganda Coffee Development Authority                                   3
Asociación de Cafés Especiales de Nicaragua                           3
Barista and Coffee Academy of Asia                                    1
Specialty Coffee Association of Indonesia                             1
Specialty Coffee Institute of Thailand                                1
Firedancer Coffee Consultants                                         1
Name: count, dtype: int64

In [299]:
df.head(2)

,Country of Origin,Company,Number of Bags,Bag Weight,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,...,Sweetness,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Certification Body
0,Colombia,Coffee Quality Union,1,35 kg,2021,8.58,8.5,8.42,8.58,8.25,...,10.0,8.58,0.0,89.33,11.8,0,0,green,3,Japan Coffee Exchange
1,Taiwan,Taiwan Coffee Laboratory,1,80 kg,2021,8.50,8.5,7.92,8.00,7.92,...,10.0,8.50,0.0,87.58,10.5,0,0,blue-green,0,Taiwan Coffee Laboratory 台灣咖啡研究室

In [300]:
df['Color'].value_counts()

Color
green            101
greenish          36
bluish-green      21
blue-green        12
yellow-green      10
brownish           9
pale yellow        6
yellow green       5
yellowish          4
yellow- green      1
browish-green      1
yello-green        1
Name: count, dtype: int64

In [301]:
df['Color']=df['Color'].map({'green':'green','greenish':'green','bluish-green':'blue-green','blue-green':'blue-green','yellow-green':'yellow-green','brownish':'brownish','pale yellow':'pale yellow','yellow green':'yellow-green','yellowish':'yellowish','yellow- green':'yellow-green','browish-green':'browish-green','yello-green':'yellow-green'})

In [302]:
df.head(2)

,Country of Origin,Company,Number of Bags,Bag Weight,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,...,Sweetness,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Certification Body
0,Colombia,Coffee Quality Union,1,35 kg,2021,8.58,8.5,8.42,8.58,8.25,...,10.0,8.58,0.0,89.33,11.8,0,0,green,3,Japan Coffee Exchange
1,Taiwan,Taiwan Coffee Laboratory,1,80 kg,2021,8.50,8.5,7.92,8.00,7.92,...,10.0,8.50,0.0,87.58,10.5,0,0,blue-green,0,Taiwan Coffee Laboratory 台灣咖啡研究室

In [303]:
df['Bag Weight'].value_counts()

Bag Weight
30 kg       39
60 kg       31
69 kg       25
1 kg        14
15 kg       10
5 kg        10
2 kg         8
70 kg        6
100 kg       6
50 kg        6
10 kg        5
80 kg        4
35 kg        4
20 kg        3
12 kg        3
4 kg         2
25 kg        2
90 kg        2
45 kg        2
16 kg        2
13 kg        2
22 kg        2
19200 kg     2
8 kg         2
40 kg        1
32 kg        1
200 kg       1
3 kg         1
320 kg       1
6 kg         1
104 kg       1
110 kg       1
300 kg       1
36 kg        1
24 kg        1
48 kg        1
85 kg        1
27 kg        1
59 kg        1
Name: count, dtype: int64

In [304]:
df['Bag Weight(kg)']=df['Bag Weight'].str.split(' ',expand=True)[0].astype('Float64')

In [305]:
df['Bag Weight(kg)'].value_counts()

Bag Weight(kg)
30.0       39
60.0       31
69.0       25
1.0        14
15.0       10
5.0        10
2.0         8
70.0        6
100.0       6
50.0        6
10.0        5
80.0        4
35.0        4
20.0        3
12.0        3
4.0         2
25.0        2
90.0        2
45.0        2
16.0        2
13.0        2
22.0        2
19200.0     2
8.0         2
40.0        1
32.0        1
200.0       1
3.0         1
320.0       1
6.0         1
104.0       1
110.0       1
300.0       1
36.0        1
24.0        1
48.0        1
85.0        1
27.0        1
59.0        1
Name: count, dtype: Int64

In [306]:
df.drop('Bag Weight',inplace=True,axis=1)

In [307]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country of Origin     207 non-null    object
 1   Company               207 non-null    object
 2   Number of Bags        207 non-null    int64
 3   Harvest Year          207 non-null    object
 4   Aroma                 207 non-null    float64
 5   Flavor                207 non-null    float64
 6   Aftertaste            207 non-null    float64
 7   Acidity               207 non-null    float64
 8   Body                  207 non-null    float64
 9   Balance               207 non-null    float64
 10  Uniformity            207 non-null    float64
 11  Clean Cup             207 non-null    float64
 12  Sweetness             207 non-null    float64
 13  Overall               207 non-null    float64
 14  Defects               207 non-null    float64
 15  Total Cup Points      207 non-null    float64
 16  Moisture Percentage   207 non-null    float64
 17  Category One Defects  207 non-null    int64
 18  Quakers               207 non-null    int64
 19  Color                 207 non-null    object
 20  Category Two Defects  207 non-null    int64
 21  Certification Body    207 non-null    object
 22  Bag Weight(kg)        207 non-null    Float64
dtypes: Float64(1), float64(13), int64(4), object(5)
memory usage: 37.5+ KB

In [308]:
df['qty(kg)']=df['Bag Weight(kg)'] *df['Number of Bags']

In [309]:
df.drop('Bag Weight(kg)',inplace=True,axis=1)
df.drop('Number of Bags',inplace=True,axis=1)

In [310]:
df['qty(kg)'].value_counts()

qty(kg)
2.0        14
18975.0    13
18000.0    11
19200.0    11
100.0       9
           ..
1050.0      1
26250.0     1
19050.0     1
19950.0     1
36000.0     1
Name: count, Length: 93, dtype: Int64

In [311]:
df.head(2)

,Country of Origin,Company,Harvest Year,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,...,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Certification Body,qty(kg)
0,Colombia,Coffee Quality Union,2021,8.58,8.5,8.42,8.58,8.25,8.42,10.0,...,8.58,0.0,89.33,11.8,0,0,green,3,Japan Coffee Exchange,35.0
1,Taiwan,Taiwan Coffee Laboratory,2021,8.50,8.5,7.92,8.00,7.92,8.25,10.0,...,8.50,0.0,87.58,10.5,0,0,blue-green,0,Taiwan Coffee Laboratory 台灣咖啡研究室,80.0

In [323]:
df.info(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country of Origin     207 non-null    object
 1   Company               207 non-null    object
 2   Harvest Year          207 non-null    object
 3   Aroma                 207 non-null    float64
 4   Flavor                207 non-null    float64
 5   Aftertaste            207 non-null    float64
 6   Acidity               207 non-null    float64
 7   Body                  207 non-null    float64
 8   Balance               207 non-null    float64
 9   Uniformity            207 non-null    float64
 10  Clean Cup             207 non-null    float64
 11  Sweetness             207 non-null    float64
 12  Overall               207 non-null    float64
 13  Defects               207 non-null    float64
 14  Total Cup Points      207 non-null    float64
 15  Moisture Percentage   207 non-null    float64
 16  Category One Defects  207 non-null    object
 17  Quakers               207 non-null    object
 18  Color                 207 non-null    object
 19  Category Two Defects  207 non-null    object
 20  Certification Body    207 non-null    object
 21  qty(kg)               207 non-null    Float64
dtypes: Float64(1), float64(13), object(8)
memory usage: 35.9+ KB

In [314]:
df['Category One Defects'].value_counts()

Category One Defects
0    193
1      6
2      5
3      1
4      1
5      1
Name: count, dtype: int64

In [319]:
df['Category One Defects']=df['Category One Defects'].astype(object)
df['Category Two Defects']=df['Category Two Defects'].astype(object)

In [322]:
df['Quakers']=df['Quakers'].astype(object)